apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: prometheus-blackbox-exporter
    targetRevision: 11.*
    helm:
      skipCrds: false
      valuesObject:
        serviceMonitor:
          enabled: true
          targets:
            - name: seafile                     # Human readable URL that will appear in Prometheus / AlertManager
              url: https://sea.geracorp.ru      # The URL that blackbox will scrape
              hostname: sea.geracorp.ru         # HTTP probes can accept an additional `hostname` parameter that will set `Host` header and TLS SNI
            - name: mail-biostal
              url: https://mail.biostal.ru:4040
              hostname: mail.biostal.ru
            - name: control-biostal
              url: https://control.biostal.ru:4081
              hostname: control.biostal.ru
            - name: cloud-biostal
              url: https://cloud.biostal.ru
              hostname: cloud.biostal.ru
            - name: telegram-api
              url: https://api.telegram.org/bot${vault:secret/data/alertmanager#telegram_token}/getMe
              hostname: api.telegram.org
              additionalMetricsRelabels:
              - action: replace
                replacement: https://api.telegram.org
                sourceLabels:
                  - instance
                targetLabel: instance
            # - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
            #   url: http://example.com/healthz  # The URL that blackbox will scrape
            #   hostname: example.com            # HTTP probes can accept an additional `hostname` parameter that will set `Host` header and TLS SNI
            #   labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
            #   interval: 60s                    # Scraping interval. Overrides value set in `defaults`
            #   scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
            #   module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
            #   additionalMetricsRelabels: {}    # Map of metric labels and values to add
            #   additionalRelabeling: []         # List of metric relabeling actions to run
