apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: home-pc
  namespace: monitoring
  labels:
    prometheus: home-pc
    release: prom
spec:
  scheme: HTTP
  metricsPath: /metrics
  staticConfigs:
    - labels:
        job: home-pc
      targets:
        - 10.0.0.11:4445
  relabelConfigs:
    - source_labels: [__address__]
      regex: ([^:]+)(?::\d+)?
      target_label: ip_address
      replacement: $1
      action: replace
