apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 68.*
    helm:
      skipCrds: false
      values: |-
        defaultRules:
          rules:
            kubeControllerManager: false
            kubeSchedulerAlerting: false
            kubeSchedulerRecording: false
        prometheus:
          enabled: true
          prometheusSpec:
            replicas: 1
            resources:
              limits:
                cpu: 1
                memory: 4Gi
              requests:
                cpu: 100m
                memory: 1024Mi
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
            scrapeConfigSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: nfs-client
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 32Gi
            additionalScrapeConfigs:
              - honor_labels: true
                job_name: kubernetes-pods
                kubernetes_sd_configs:
                - role: pod
                relabel_configs:
                - action: keep
                  regex: true
                  source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_scrape
                - action: replace
                  regex: (https?)
                  source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_scheme
                  target_label: __scheme__
                - action: replace
                  regex: (.+)
                  source_labels:
                  - __meta_kubernetes_pod_annotation_prometheus_io_path
                  target_label: __metrics_path__
                - action: replace
                  regex: (.+?)(?::\d+)?;(\d+)
                  replacement: $1:$2
                  source_labels:
                  - __address__
                  - __meta_kubernetes_pod_annotation_prometheus_io_port
                  target_label: __address__
                - action: labelmap
                  regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
                  replacement: __param_$1
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - action: replace
                  source_labels:
                  - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                  - __meta_kubernetes_pod_name
                  target_label: pod
                - action: drop
                  regex: Pending|Succeeded|Failed|Completed
                  source_labels:
                  - __meta_kubernetes_pod_phase
        grafana:
          enabled: true
          sidecar:
            dashboards:
              annotations:
                grafana_folder: "Kubernetes"
              folderAnnotation: "grafana_folder"
              provider:
                foldersFromFilesStructure: true
          persistence:
            enabled: true
            type: pvc
            accessModes:
              - ReadWriteOnce
            size: 5Gi
            storageClassName: nfs-client
        alertmanager:
          enabled: true
          config:
            global:
              resolve_timeout: 5m
            inhibit_rules:
              - source_matchers:
                  - 'severity = critical'
                target_matchers:
                  - 'severity =~ warning|info'
                equal:
                  - 'namespace'
                  - 'alertname'
              - source_matchers:
                  - 'severity = warning'
                target_matchers:
                  - 'severity = info'
                equal:
                  - 'namespace'
                  - 'alertname'
              - source_matchers:
                  - 'alertname = InfoInhibitor'
                target_matchers:
                  - 'severity = info'
                equal:
                  - 'namespace'
              - target_matchers:
                  - 'alertname = InfoInhibitor'
            route:
              group_by: ['namespace']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'telegram'
              routes:
              - receiver: 'telegram'
                matchers:
                  - alertname = "Watchdog"
            receivers:
            - name: 'telegram'
              telegram_configs:
              - bot_token_file: '/etc/alertmanager/secrets/alertmanager-secrets/telegram-bot-token'
                api_url: 'https://api.telegram.org'
                chat_id: 282307402
                parse_mode: ''
            templates:
            - '/etc/alertmanager/config/*.tmpl'
          alertmanagerSpec:
            secrets:
            - alertmanager-secrets
          templateFiles:
            template_1.tmpl: |-
              {{ define "telegram.default.message" }}
              Alert:
              {{ range .Alerts }}
                *Alert:* {{ .Annotations.summary }}
                *Description:* {{ .Annotations.description }}
                *Severity:* {{ .Labels.severity }}
                *Status:* {{ .Status }}
                *Starts At:* {{ .StartsAt }}
                *Ends At:* {{ .EndsAt }}
              {{ end }}
              {{ end }}
        kubeEtcd:
          enabled: true
          service:
            selector:
              k8s-app: kube-controller-manager # Fix selector for kube-etcd for Talos (set itentionally to kube-controller-manager because all master nodes has the same roles)
          serviceMonitor:
            relabelings:   # Add nodename label
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                separator: ;
                regex: ^(.*)$
                targetLabel: nodename
                replacement: $1
                action: replace
            metricRelabelings:   # Remove pod label
              - action: labeldrop
                regex: pod
        kubeProxy:
          enabled: true
          service:
            enabled: true
            port: 10249
            targetPort: 10249
            selector:
              k8s-app: kube-proxy
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  commonName: mon.geracorp.ru
  secretName: grafana-cert
  dnsNames:
    - mon.geracorp.ru
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-tls
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`mon.geracorp.ru`)
    kind: Rule
    services:
    - name: kube-prometheus-stack-grafana
      port: 80
  tls:
    secretName: grafana-cert
