apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
stringData:
  telegram-bot-token: vault:secret/data/alertmanager#telegram_token
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-basic-auth
  namespace: monitoring
stringData:
  username: prometheus
  password: vault:secret/data/metrics#basic_auth_password
type: Opaque
