apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegram-api-monitor-test
  namespace: monitoring
spec:
  endpoints:
    - honorTimestamps: true
      interval: 30s
      metricRelabelings:
        - action: replace
          replacement: https://api.telegram.org
          sourceLabels:
            - instance
          targetLabel: instance
        - action: replace
          replacement: telegram-api
          sourceLabels:
            - target
          targetLabel: target
      params:
        hostname:
          - api.telegram.org
        module:
          - http_2xx
        target:
          - "https://api.telegram.org/bot${vault:secret/data/alertmanager#telegram_token}/getMe"
      path: /probe
      port: http
      scheme: http
      scrapeTimeout: 30s
  jobLabel: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-blackbox-exporter
      app.kubernetes.io/name: prometheus-blackbox-exporter
