apiVersion: v1
kind: ConfigMap
metadata:
  name: github2telegram-config
  namespace: tools
data:
  config_template.yaml: |
    # Port for Debug info
    # listen: ":6060"
    logger:
    - logger: ''
      file: stdout
      level: info
      encoding: json
      encoding_time: iso8601
      encoding_duration: seconds
    # Only sqlite3 was tested
    database_type: sqlite3
    database_url: "/db/github2telegram.sqlite3"
    database_login: ''
    database_password: ''
    # Username that will have access to bot controls. Currently only one can be specified
    admin_username: "$ADMIN_USER"
    # Please note, that github might ban bot if you are polling too quick, safe option is about 10 minutes for moderate amount of feeds (100)
    polling_interval: "30m"
    endpoints:
      # Currently only telegram is supported
      telegram:
        token: "$BOT_TOKEN"
        type: telegram
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github2telegram-pvc
  namespace: tools
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: github2telegram
  name: github2telegram
  namespace: tools
spec:
  selector:
    matchLabels:
      app: github2telegram
  serviceName: github2telegram
  replicas: 1
  template:
    metadata:
      labels:
        app: github2telegram
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'github2telegram'
        vault.hashicorp.com/agent-inject-secret-config: 'secret/tools/github2telegram-bot'
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/tools/github2telegram-bot" -}}
          export ADMIN_USER="{{.Data.ADMIN_USER}}"
          export BOT_TOKEN="{{.Data.BOT_TOKEN}}"
          {{- end }}
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      serviceAccountName: internal-app
      containers:
        - name: github2telegram
          image: gerain/github2telegram:test4
          imagePullPolicy: IfNotPresent
          command:
            ['sh', '-c']
          args:
            ['export $(cat /vault/secrets/config | xargs) && envsubst < config_template.yaml > config.yaml && /app/github2telegram']
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - name: github2telegram-config-volume
              mountPath: /app/config_template.yaml
              subPath: config_template.yaml
            - name: github2telegram-pv
              mountPath: /db
      volumes:
        - name: github2telegram-config-volume
          configMap:
            defaultMode: 420
            name: github2telegram-config
        - name: github2telegram-pv
          persistentVolumeClaim:
            claimName: github2telegram-pvc
