---
apiVersion: v1
kind: Namespace
metadata:
  name: tabby
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tabby-web
  name: tabby-web
  namespace: tabby
spec:
  selector:
    matchLabels:
      app: tabby-web
  replicas: 1
  template:
    metadata:
      labels:
        app: tabby-web
    spec:
      containers:
        - name: tabby-web
          image: ghcr.io/eugeny/tabby-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: tabby-web-port
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: DATABASE_URL
              value: "sqlite:////app-dist/db.sqlite3"
            - name: APP_DIST_STORAGE
              value: "file:///app-dist"
            - name: PORT
              value: "8000"
            - name: DEBUG
              value: "True"
            - name: SOCIAL_AUTH_GITHUB_KEY
              value: vault:secret/data/tabby#SOCIAL_AUTH_GITHUB_KEY
            - name: SOCIAL_AUTH_GITHUB_SECRET
              value: vault:secret/data/tabby#SOCIAL_AUTH_GITHUB_SECRET
          volumeMounts:
            - name: tabby-web-data
              mountPath: /app-dist
      volumes:
        - name: tabby-web-data
          persistentVolumeClaim:
            claimName: tabby-web-data
---
apiVersion: v1
kind: Service
metadata:
  name: tabby-web
  namespace: tabby
spec:
  ports:
    - name: tabby-web-port
      port: 8000
      protocol: TCP
      targetPort: tabby-web-port
  selector:
    app: tabby-web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tabby-web-data
  namespace: tabby
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tabby-tls
  namespace: tabby
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`tabby.local.geracorp.work`)
    kind: Rule
    services:
    - name: tabby-web
      port: tabby-web-port
  tls: {}
