apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vault-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
spec:
  groups:
    - name: vault.rules
      rules:
        - alert: VaultAutopilotNodeHealthy
          # Set to 1 if Autopilot considers all nodes healthy
          # https://www.vaultproject.io/docs/internals/telemetry#integrated-storage-raft-autopilot
          expr: vault_autopilot_healthy < 1
          for: 1m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: Autopilot Vault Raft node unhealthy
            description: At least one of the Autopilot Vault Raft nodes is unhealthy
        - alert: VaultLeadershipLoss
          expr: sum(increase(vault_core_leadership_lost_count{job="vault-cluster"}[1h])) > 5
          for: 1m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: High frequency of Vault leadership losses
            description: There have been more than 5 Vault leadership losses in the past 1h
        - alert: VaultLeadershipStepDowns
          expr: sum(increase(vault_core_step_down_count{job="vault-cluster"}[1h])) > 5
          for: 1m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: High frequency of Vault leadership step downs
            description: There have been more than 5 Vault leadership step downs in the past 1h
        - alert: VaultLeadershipSetupFailures
          expr: sum(increase(vault_core_leadership_setup_failed{job="vault-cluster"}[1h])) > 5
          for: 1m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: High frequency of Vault leadership setup failures
            description: There have been more than 5 Vault leadership setup failures in the past 1h
        - alert: VaultRequestFailures
          expr: increase(vault_audit_log_request_failure[5m]) > 0
          for: 15m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: High frequency of failed Vault requests
            description: There has been an increased number of failed Vault requests in the last 15 minutes
        - alert: VaultResponseFailures
          expr: increase(vault_audit_log_response_failure[5m]) > 0
          for: 15m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: High frequency of failed Vault responses
            description: There has been an increased number of failed Vault responses in the last 15 minutes
        - alert: VaultTokenCreate
          expr: increase(vault_token_create_count[5m]) > 100
          for: 15m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: High frequency of created Vault token
            description: There has been an increased number of Vault token creation in the last 15 minutes
        - alert: VaultTokenStore
          expr: increase(vault_token_store_count[5m]) > 100
          for: 15m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: High frequency of stored Vault token
            description: There has been an increased number of Vault token storing in the last 15 minutes
        - alert: VaultLowFailureTolerance
          expr: vault_autopilot_failure_tolerance == 0
          for: 5m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: Vault Raft Cluster Failure Tolerance Critical
            description: Vault Raft cluster has a failure tolerance of 0
        - alert: VaultSealed
          expr: vault_core_unsealed == 0
          for: 0m
          labels:
            severity: critical
            service: infrastructure
          annotations:
            summary: Vault sealed (instance {{ $labels.instance }})
            description: "Vault instance is sealed on {{ $labels.instance }} VALUE = {{ $value }}"
        - alert: VaultTooManyInfinityTokens
          expr: vault_token_count_by_ttl{creation_ttl="+Inf"} > 10
          for: 5m
          labels:
            severity: warning
            service: infrastructure
          annotations:
            summary: Vault too many infinity tokens (instance {{ $labels.instance }})
            description: "Too many infinity tokens {{ $labels.instance }}: {{ $value }}"
        - alert: VaultTooManyLeases
          expr: vault_expire_num_leases > 128000
          for: 5m
          labels:
            severity: warning
            service: infrastructure
          annotations:
            summary: Vault has too many unexpired leases (instance {{ $labels.instance }})
            description: "High lease counts ({{ $value }}) can cause degradation in system performance"
