apiVersion: v1
kind: ConfigMap
metadata:
  name: github2telegram-config
  namespace: tools
data:
  config_template.yaml: |
    # Port for Debug info
    # listen: ":6060"
    logger:
    - logger: ''
      file: stdout
      level: info
      encoding: json
      encoding_time: iso8601
      encoding_duration: seconds
    # Only sqlite3 was tested
    database_type: sqlite3
    database_url: "/db/github2telegram.sqlite3"
    database_login: ''
    database_password: ''
    # Username that will have access to bot controls. Currently only one can be specified
    admin_username: "$ADMIN_USER"
    # Please note, that github might ban bot if you are polling too quick, safe option is about 10 minutes for moderate amount of feeds (100)
    polling_interval: "30m"
    endpoints:
      # Currently only telegram is supported
      telegram:
        token: "$BOT_TOKEN"
        type: telegram
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github2telegram
  name: github2telegram
  namespace: tools
spec:
  selector:
    matchLabels:
      app: github2telegram
  replicas: 1
  template:
    metadata:
      labels:
        app: github2telegram
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      serviceAccountName: default
      containers:
        - name: github2telegram
          image: gerain/github2telegram:v0.0.2-1
          imagePullPolicy: IfNotPresent
          command:
            ['sh', '-c']
          args:
            ['envsubst < config_template.yaml > config.yaml && /app/github2telegram']
          resources:
            limits:
              memory: 512Mi
              cpu: "750m"
            requests:
              memory: 256Mi
              cpu: "500m"
          env:
          - name: ADMIN_USER
            value: vault:secret/data/github2telegram-bot#ADMIN_USER
          - name: BOT_TOKEN
            value: vault:secret/data/github2telegram-bot#BOT_TOKEN
          volumeMounts:
            - name: github2telegram-pv
              mountPath: /db
            - name: github2telegram-config-volume
              mountPath: /app/config_template.yaml
              subPath: config_template.yaml
      volumes:
        - name: github2telegram-config-volume
          configMap:
            name: github2telegram-config
        - name: github2telegram-pv
          persistentVolumeClaim:
            claimName: github2telegram-pv
  # volumeClaimTemplates:
  # - metadata:
  #     name: github2telegram-pv
  #     namespace: tools
  #   spec:
  #     accessModes: ["ReadWriteMany"]
  #     resources:
  #       requests:
  #         storage: 50M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github2telegram-pv
  namespace: tools
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
