apiVersion: v1
kind: Secret
metadata:
  name: github2telegram-creds
  namespace: tools
  annotations:
    avp.kubernetes.io/path: "secret/tools/github2telegram-bot"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
data:
  ADMIN_USER: <ADMIN_USER>
  BOT_TOKEN: <BOT_TOKEN>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github2telegram-config
  namespace: tools
data:
  config_template.yaml: |
    # Port for Debug info
    # listen: ":6060"
    logger:
    - logger: ''
      file: stdout
      level: info
      encoding: json
      encoding_time: iso8601
      encoding_duration: seconds
    # Only sqlite3 was tested
    database_type: sqlite3
    database_url: "/db/github2telegram.sqlite3"
    database_login: ''
    database_password: ''
    # Username that will have access to bot controls. Currently only one can be specified
    admin_username: "$ADMIN_USER"
    # Please note, that github might ban bot if you are polling too quick, safe option is about 10 minutes for moderate amount of feeds (100)
    polling_interval: "30m"
    endpoints:
      # Currently only telegram is supported
      telegram:
        token: "$BOT_TOKEN"
        type: telegram
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: github2telegram
  name: github2telegram
  namespace: tools
spec:
  selector:
    matchLabels:
      app: github2telegram
  serviceName: github2telegram
  replicas: 1
  template:
    metadata:
      labels:
        app: github2telegram
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      serviceAccountName: internal-app
      containers:
        - name: github2telegram
          image: gerain/github2telegram:test4
          imagePullPolicy: IfNotPresent
          command:
            ['sh', '-c']
          args:
            ['envsubst < config_template.yaml > config.yaml && /app/github2telegram']
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: github2telegram-creds
                key: ADMIN_USER
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: github2telegram-creds
                key: BOT_TOKEN
          volumeMounts:
            - name: github2telegram-pv
              mountPath: /db
            - name: github2telegram-config-volume
              mountPath: /app/config_template.yaml
              subPath: config_template.yaml
      volumes:
        - name: github2telegram-config-volume
          configMap:
            name: github2telegram-config
  volumeClaimTemplates:
  - metadata:
      name: github2telegram-pv
      namespace: tools
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 50M
