apiVersion: v1
kind: Secret
metadata:
  name: es-credentials
  namespace: fluentd
  annotations:
    avp.kubernetes.io/path: "secret/tools/elasticsearch/fluentd"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
stringData:
  ES_USERNAME: <ES_USERNAME>
  ES_PASSWORD: <ES_PASSWORD>
