# Application manifest
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
spec:
  destination:
    name: in-cluster
    namespace: openclaw
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: "*"
      kind: ConfigMap
      name: openclaw-config
      jsonPointers:
        - /data
  source:
    repoURL: 'https://serhanekicii.github.io/openclaw-helm'
    chart: openclaw
    targetRevision: 1.5.*
    helm:
      skipCrds: false
      valuesObject:
        app-template:
          openclawVersion: "2026.4.25"
          # chromiumVersion: "148.0.7778.56"
          # defaultPodOptions:
          #   nodeSelector:
          #     kubernetes.io/arch: "arm64"
          #   tolerations:
          #     - key: "dedicated"
          #       operator: "Equal"
          #       value: "arm64"
          #       effect: "NoSchedule"
          controllers:
            main:
              containers:
                main:
                  securityContext:
                    readOnlyRootFilesystem: false
                  env:
                    # HOME: /home/node/.openclaw
                    NPM_CONFIG_CACHE: /home/node/.openclaw/.npm
                  envFrom:
                    - secretRef:
                        name: openclaw-env-secret
                  resources:
                    requests:
                      # @schema type:string;default:200m
                      cpu: 200m
                      # @schema type:string;default:512Mi
                      memory: 512Mi
                    limits:
                      # @schema type:string;default:2000m
                      cpu: 2000m
                      # @schema type:string;default:2Gi
                      memory: 4Gi
