apiVersion: v1
kind: Secret
metadata:
  name: docker-token
  namespace: default
  annotations:
    avp.kubernetes.io/path: "secret/tools/docker_registry"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
data:
  token: <value>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniblog
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniblog
  template:
    metadata:
      labels:
        app: miniblog
    spec:
      containers:
        - name: miniblog
          image: gerain/miniblog.core:master-6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
          - name: DOCKER_ROKEN
            valueFrom:
              secretKeyRef:
                name: docker-token
                key: token
