apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
  annotations:
    avp.kubernetes.io/path: "secret/tools/docker_registry"
    avp.kubernetes.io/kv-version: "1"
data:
  .dockerconfigjson: <dockerconfigjson>
type: kubernetes.io/dockerconfigjson
