apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
stringData:
  .dockerconfigjson: '{"auths":{"docker-registry.local.geracorp.work":{"auth":"vault:secret/data/docker_registry#value"}}}'
type: kubernetes.io/dockerconfigjson
