apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
  annotations:
    avp.kubernetes.io/path: "secret/data/docker_registry"
    avp.kubernetes.io/kv-version: "2"
stringData:
  .dockerconfigjson: <dockerconfigjson>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-bind-cred
  namespace: jenkins
  annotations:
    avp.kubernetes.io/path: "secret/data/lldap"
    avp.kubernetes.io/kv-version: "2"
type: Opaque
stringData:
  user: <bind_jenkins_user>
  password: <bind_jenkins_password>
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-jenkins-token
  namespace: jenkins
  annotations:
    avp.kubernetes.io/path: "secret/data/jenkins/vault-token"
    avp.kubernetes.io/kv-version: "2"
type: Opaque
stringData:
  token: <token>
