apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
  annotations:
    avp.kubernetes.io/path: "secret/data/docker_registry"
    avp.kubernetes.io/kv-version: "2"
stringData:
  .dockerconfigjson: <dockerconfigjson>
type: kubernetes.io/dockerconfigjson
