apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
  annotations:
    avp.kubernetes.io/path: "secret/tools/docker_registry"
    avp.kubernetes.io/kv-version: "1"
stringData:
  .dockerconfigjson: <dockerconfigjson>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: lldap-bind-cred
  namespace: jenkins
  annotations:
    avp.kubernetes.io/path: "secret/tools/lldap"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
stringData:
  user: <user>
  password: <password>
