apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItcmVnaXN0cnkubG9jYWwuZ2VyYWNvcnAud29yayI6eyJhdXRoIjoiZG1GMWJIUTZjMlZqY21WMEwyUmhkR0V2Wkc5amEyVnlYM0psWjJsemRISjVJMlJ2WTJ0bGNtTnZibVpwWjJwemIyND0ifX19
type: kubernetes.io/dockerconfigjson
