apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
data:
  .dockerconfigjson: vault:secret/data/docker_registry#dockerconfigjson
type: kubernetes.io/dockerconfigjson
