apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-geracorp-login
  namespace: jenkins
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItcmVnaXN0cnkubG9jYWwuZ2VyYWNvcnAud29yayI6eyJhdXRoIjoidmF1bHQ6c2VjcmV0L2RhdGEvZG9ja2VyX3JlZ2lzdHJ5I3ZhbHVlIn19fQ==
type: kubernetes.io/dockerconfigjson
