---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-http
  namespace: jenkins
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: jenkins-http
  selector:
    app: jenkins
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-local-tls
  namespace: jenkins
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`jenkins.local.geracorp.work`)
    kind: Rule
    services:
    - name: jenkins-http
      port: 8080
  tls: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  ports:
    - port: 50000
      protocol: TCP
      targetPort: jenkins-agent
  selector:
    app: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jk-agnt-packer
  namespace: jenkins
spec:
  ports:
    - port: 8336
      protocol: TCP
      targetPort: jenkins-agt-pk
  selector:
    jenkins/label: jenkins-nomad-worker

