apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lldap
  name: lldap
  namespace: lldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lldap
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.bank-vault:8200"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        #vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      serviceAccountName: default
      containers:
        - env:
            - name: GID
              value: "1001"
            - name: LLDAP_JWT_SECRET
              value: vault:secret/data/lldap#lldap-jwt-secret
            - name: LLDAP_LDAP_BASE_DN
              value: vault:secret/data/lldap#base-dn
            - name: LLDAP_LDAP_USER_PASS
              value: vault:secret/data/lldap#lldap-ldap-admin-pass
            - name: TZ
              value: CET
            - name: UID
              value: "1001"
          image: nitnelave/lldap:latest
          name: lldap
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 3890
            - containerPort: 17170
          volumeMounts:
            - mountPath: /data
              name: lldap-data
      restartPolicy: Always
      volumes:
        - name: lldap-data
          persistentVolumeClaim:
            claimName: lldap-data
        - name: lldap-credentials
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lldap
  name: lldap-data
  namespace: lldap
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
