apiVersion: v1
kind: Secret
metadata:
  name: lldap-credentials
  namespace: lldap
  annotations:
    avp.kubernetes.io/path: "secret/tools/lldap"
    avp.kubernetes.io/kv-version: "1"
stringData:
  lldap-jwt-secret: <lldap-jwt-secret>
  lldap-ldap-user-pass: <lldap-ldap-admin-pass>
  base-dn: <base-dn>
