apiVersion: v1
kind: Service
metadata:
  labels:
    app: lldap-service
  name: lldap-service
  namespace: lldap
spec:
  ports:
    - name: "3890"
      port: 3890
      targetPort: 3890
    - name: "17170"
      port: 17170
      targetPort: 17170
  selector:
    app: lldap
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lldap-https
  namespace: lldap
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`lldap.local.geracorp.work`)
    kind: Rule
    services:
    - name: lldap-service
      port: 17170
  tls:
    secretName: letsencrypt-cloud-production-tls
