apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tabby-gateway
  name: tabby-gateway
  namespace: tabby
spec:
  selector:
    matchLabels:
      app: tabby-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: tabby-gateway
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault-cluster.local.geracorp.work"
        vault.security.banzaicloud.io/vault-role: "default"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        #vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      containers:
        - name: tabby-gateway
          image: ghcr.io/eugeny/tabby-connection-gateway:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: tabby-gateway
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: TABBY_AUTH_TOKEN
              value: vault:secret/data/tabby#TABBY_AUTH_TOKEN
          args: ["--token-auth", "--host=0.0.0.0"]
          volumeMounts:
            - name: tabby-web-cert
              mountPath: /crts
      volumes:
        - name: tabby-web-cert
          secret:
            secretName: tabby-web-cert
---
apiVersion: v1
kind: Service
metadata:
  name: tabby-gateway
  namespace: tabby
spec:
  ports:
    - name: tabby-gateway
      port: 9000
      protocol: TCP
      targetPort: tabby-gateway
  selector:
    app: tabby-gateway
