
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7.5-alpine
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_USERNAME
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: influxdb-secret
                  key: DOCKER_INFLUXDB_INIT_PASSWORD
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: geracorp
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: proxmox
          ports:
            - containerPort: 8086
              name: http-influxdb
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
        namespace: influxdb
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5G
