apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secret
  namespace: influxdb
  annotations:
    avp.kubernetes.io/path: "secret/tools/influxdb"
    avp.kubernetes.io/kv-version: "1"
type: Opaque
stringData:
  DOCKER_INFLUXDB_INIT_USERNAME: <DOCKER_INFLUXDB_INIT_USERNAME>
  DOCKER_INFLUXDB_INIT_PASSWORD: <DOCKER_INFLUXDB_INIT_PASSWORD>
