apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: influxdb
spec:
  ports:
    - name: influxdb
      port: 8086
      targetPort: http-influxdb
  selector:
      app: influxdb
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb-https
  namespace: influxdb
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`influxdb.local.geracorp.work`)
    kind: Rule
    services:
    - name: influxdb-service
      port: influxdb
  tls:
    secretName: letsencrypt-cloud-production-tls
