apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: in-cluster
    namespace: prometheus
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 60.0.0
    chart: kube-prometheus-stack
  project: default
  syncPolicy:
    automated:
      prune: true
      selfheal: true
    syncOptions:
      - CreateNamespace=true
