apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: vault-01
  namespace: monitoring
  labels:
    prometheus: test
    release: prom
spec:
  scheme: HTTP
  metricsPath: /v1/sys/metrics
  staticConfigs:
    - labels:
        job: vault-01
      targets:
        - 192.168.1.160:8200
        - 192.168.1.161:8200
        - 192.168.1.162:8200
