apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: vault-cluster
  namespace: monitoring
  labels:
    prometheus: vault
    release: prom
spec:
  scheme: HTTP
  metricsPath: /v1/sys/metrics
  staticConfigs:
    - labels:
        job: vault-cluster
      targets:
        - 192.168.1.160:8200
        - 192.168.1.161:8200
        - 192.168.1.162:8200
