apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: v2ray
  namespace: monitoring
  labels:
    prometheus: v2ray
    release: prom
spec:
  scheme: HTTPS
  metricsPath: /v2ray/scrape
  basicAuth:
    username:
      name: metrics-basic-auth
      key: username
    password:
      name: metrics-basic-auth
      key: password
  staticConfigs:
    - labels:
        job: v2ray
      targets:
        - trol.geracorp.org:8844
        - homs.geracorp.org:8844
